name: Test dot notation
on:
  push:
    branches: [ "**" ]
jobs:
  test-linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ '3.8' ]
    steps:
    - uses: actions/checkout@v2
    - name: Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependencies
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add - && echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
        sudo apt-get update
        sudo apt-get -y install mongodb-org python3-wheel python3-pip
        python -m pip install -q codecov flake8
        pip install -q -r requirements.txt
    - name: Run MongoDB (background)
      run: |
        /usr/bin/mongod &
        sleep 2
    - name: Run REST API (background)
      run: |
        python3 api/dms3.py &
        sleep 2
    - name: PyTest
      timeout-minutes: 1
      run: |
        python -m pytest -v api/
